# wrangler.toml

name = "planner"
main = "./dist/_worker.js"
compatibility_date = "2024-05-01" # Or a recent date

[[d1_databases]]
binding = "DB"
database_name = "planner-db"
database_id = "ca3a5faa-f6c2-4fbd-b3ee-fd9cc0067d67"